export const publicListings = [
  {
    id: 1,
    make: "Toyota",
    model: "Camry",
    year: 2018,
    contact: "John Doe",
    price: 100000,
    mileage: 10,
    power: 166,
    speed: 126,
    images: [
      "https://imgd.aeplcdn.com/642x361/cw/ec/34002/Toyota-Camry-Exterior-125206.jpg?wm=0&q=75",
    ],
    title: "Toyota Camry for Sale",
    description: "Well-maintained Camry for sale",
    driven: 5715,
    damages: 2,
    originalColor: "white",
    accidents: 1,
    owners: 3,
    registration: "Bihar, India",
    tags: "Best Value",
  },
  {
    id: 2,
    make: "Honda",
    model: "Accord",
    year: 2015,
    contact: "Jane Smith",
    price: 85000,
    mileage: 50,
    power: 185,
    speed: 132,
    images: [
      "https://ic1.maxabout.us/autos/cars_india/honda-5/2011-new-accord-731-2011-new-accordmt.jpg",
    ],
    title: "Honda Accord in Excellent Condition",
    description: "Low mileage and well-maintained Accord",
    driven: 12000,
    damages: 0,
    originalColor: "silver",
    accidents: 0,
    owners: 1,
    registration: "California, USA",
    tags: "Reliable",
  },
  {
    id: 3,
    make: "Ford",
    model: "Mustang",
    year: 2020,
    contact: "Michael Johnson",
    price: 150000,
    mileage: 5,
    power: 450,
    speed: 155,
    images: [
      "https://gomechanic.in/blog/wp-content/uploads/2019/11/2020-ford-mustang.jpg",
    ],
    title: "2020 Ford Mustang GT",
    description: "High-performance Mustang with low mileage",
    driven: 2000,
    damages: 0,
    originalColor: "orange",
    accidents: 0,
    owners: 2,
    registration: "New York, USA",
    tags: "Sports Car",
  },
  {
    id: 4,
    make: "Chevrolet",
    model: "Cruze",
    year: 2017,
    contact: "Emily Davis",
    price: 75000,
    mileage: 30,
    power: 153,
    speed: 120,
    images: ["https://cdni.autocarindia.com/ExtraImages/20160116124256_1.jpg"],
    title: "Chevrolet Cruze for Sale",
    description: "Well-maintained and fuel-efficient sedan",
    driven: 8000,
    damages: 1,
    originalColor: "Silver",
    accidents: 1,
    owners: 2,
    registration: "Texas, USA",
    tags: "Economical",
  },
  {
    id: 5,
    make: "BMW",
    model: "X5",
    year: 2019,
    contact: "Robert Wilson",
    price: 200000,
    mileage: 15,
    power: 335,
    speed: 155,
    images: [
      "https://hips.hearstapps.com/hmg-prod/images/2019-bmw-x5-gallery-lead-1544808509.jpg",
    ],
    title: "Luxurious BMW X5 SUV",
    description: "Top-of-the-line SUV with low mileage",
    driven: 5000,
    damages: 0,
    originalColor: "white",
    accidents: 0,
    owners: 1,
    registration: "London, UK",
    tags: "Luxury",
  },
  {
    id: 6,
    make: "Audi",
    model: "A4",
    year: 2016,
    contact: "Sophia Anderson",
    price: 90000,
    mileage: 40,
    power: 190,
    speed: 130,
    images: [
      "https://www.carblogindia.com/wp-content/uploads/2016/01/2016-audi-a4-blue-official-images-5.jpg",
    ],
    title: "Audi A4 Sedan",
    description: "Stylish and well-maintained sedan",
    driven: 10000,
    damages: 0,
    originalColor: "blue",
    accidents: 0,
    owners: 2,
    registration: "Berlin, Germany",
    tags: "Premium",
  },
  {
    id: 7,
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2021,
    contact: "David Thompson",
    price: 250000,
    mileage: 2,
    power: 255,
    speed: 145,
    images: [
      "https://cdni.autocarindia.com/ExtraImages/20210223072553_Mercedes_Benz_C_class_2021_front.jpg",
    ],
    title: "2021 Mercedes-Benz C-Class",
    description: "Brand new luxury sedan with low mileage",
    driven: 100,
    damages: 0,
    originalColor: "Silver",
    accidents: 0,
    owners: 1,
    registration: "Paris, France",
    tags: "High-End",
  },
  {
    id: 8,
    make: "Volkswagen",
    model: "Golf",
    year: 2015,
    contact: "Olivia Martinez",
    price: 60000,
    mileage: 55,
    power: 148,
    speed: 125,
    images: ["https://i.ytimg.com/vi/w2XN_Huj_8s/sddefault.jpg"],
    title: "Volkswagen Golf Hatchback",
    description: "Reliable and fuel-efficient hatchback",
    driven: 15000,
    damages: 1,
    originalColor: "Silver",
    accidents: 1,
    owners: 3,
    registration: "Madrid, Spain",
    tags: "Compact",
  },
  {
    id: 9,
    make: "Hyundai",
    model: "Elantra",
    year: 2017,
    contact: "Daniel Brown",
    price: 70000,
    mileage: 45,
    power: 147,
    speed: 122,
    images: [
      "https://gaadiwaadi.com/wp-content/uploads/2016/11/2016-hyundai-elantra-petrol-review-e1479811116407.jpg",
    ],
    title: "Hyundai Elantra for Sale",
    description: "Well-maintained and spacious sedan",
    driven: 9000,
    damages: 0,
    originalColor: "Silver",
    accidents: 0,
    owners: 2,
    registration: "California, USA",
    tags: "Affordable",
  },
  {
    id: 10,
    make: "Kia",
    model: "Sorento",
    year: 2019,
    contact: "Sophia Johnson",
    price: 120000,
    mileage: 25,
    power: 185,
    speed: 130,
    images: [
      "https://cdn.jdpower.com/ArticleImages/2019%20Kia%20Sorento%2013268%20730.jpg",
    ],
    title: "2019 Kia Sorento SUV",
    description: "Spacious and reliable SUV with moderate mileage",
    driven: 6000,
    damages: 0,
    originalColor: "Black",
    accidents: 0,
    owners: 1,
    registration: "Texas, USA",
    tags: "Family-Friendly",
  },
  {
    id: 11,
    make: "Lexus",
    model: "RX",
    year: 2022,
    contact: "William Taylor",
    price: 280000,
    mileage: 5,
    power: 295,
    speed: 150,
    images: [
      "https://media.ed.edmunds-media.com/lexus/rx-350/2021/oem/2021_lexus_rx-350_4dr-suv_f-sport_fq_oem_1_1600.jpg",
    ],
    title: "Brand New Lexus RX SUV",
    description: "Luxury SUV with advanced features and low mileage",
    driven: 200,
    damages: 0,
    originalColor: "Silver",
    accidents: 0,
    owners: 1,
    registration: "New York, USA",
    tags: "High-End",
  },
  {
    id: 12,
    make: "Tesla",
    model: "Model 3",
    year: 2020,
    contact: "Emma Clark",
    price: 350000,
    mileage: 10,
    power: 450,
    speed: 160,
    images: ["https://etimg.etb2bimg.com/photo/71967465.cms"],
    title: "Electric Tesla Model 3",
    description: "Eco-friendly and high-performance electric car",
    driven: 1000,
    damages: 0,
    originalColor: "Blue",
    accidents: 0,
    owners: 1,
    registration: "California, USA",
    tags: "Electric",
  },
  {
    id: 13,
    make: "Nissan",
    model: "Altima",
    year: 2016,
    contact: "James Walker",
    price: 80000,
    mileage: 60,
    power: 182,
    speed: 128,
    images: [
      "https://media.ed.edmunds-media.com/nissan/altima/2016/oem/2016_nissan_altima_sedan_25-sr_fq_oem_1_1600.jpg",
    ],
    title: "Nissan Altima Sedan",
    description: "Reliable sedan with decent mileage",
    driven: 18000,
    damages: 1,
    originalColor: "blue",
    accidents: 1,
    owners: 2,
    registration: "Texas, USA",
    tags: "Affordable",
  },
  {
    id: 14,
    make: "Chevrolet",
    model: "Tahoe",
    year: 2019,
    contact: "Isabella Moore",
    price: 180000,
    mileage: 20,
    power: 355,
    speed: 140,
    images: ["https://i.ytimg.com/vi/VPNCpRBO8Go/maxresdefault.jpg"],
    title: "2019 Chevrolet Tahoe SUV",
    description: "Spacious and powerful SUV for all purposes",
    driven: 7000,
    damages: 0,
    originalColor: "Black",
    accidents: 0,
    owners: 1,
    registration: "California, USA",
    tags: "Versatile",
  },
  {
    id: 15,
    make: "Subaru",
    model: "Outback",
    year: 2017,
    contact: "Ethan Wilson",
    price: 90000,
    mileage: 35,
    power: 175,
    speed: 125,
    images: [
      "https://media.ed.edmunds-media.com/subaru/outback/2017/oem/2017_subaru_outback_wagon_25i-limited_fq_oem_1_1600.jpg",
    ],
    title: "Subaru Outback AWD",
    description: "Reliable and capable all-wheel drive wagon",
    driven: 12000,
    damages: 1,
    originalColor: "Silver",
    accidents: 1,
    owners: 2,
    registration: "New York, USA",
    tags: "Adventure",
  },
  {
    id: 16,
    make: "Ford",
    model: "F-150",
    year: 2020,
    contact: "Mia Thompson",
    price: 280000,
    mileage: 15,
    power: 375,
    speed: 150,
    images: [
      "https://img.autoabc.lv/Ford-F150/Ford-F150_2020_Apvidus_22111735402.jpg",
    ],
    title: "2020 Ford F-150 Pickup Truck",
    description: "Powerful and versatile pickup truck with low mileage",
    driven: 5000,
    damages: 0,
    originalColor: "blue",
    accidents: 0,
    owners: 1,
    registration: "Texas, USA",
    tags: "Utility",
  },
  {
    id: 17,
    make: "Toyota",
    model: "Rav4",
    year: 2019,
    contact: "Liam Anderson",
    price: 140000,
    mileage: 25,
    power: 203,
    speed: 135,
    images: [
      "https://s.wsj.net/public/resources/images/B3-DT438_RUMBLE_P_20190418112406.jpg",
    ],
    title: "2019 Toyota Rav4 SUV",
    description: "Reliable and efficient SUV for everyday use",
    driven: 8000,
    damages: 0,
    originalColor: "White",
    accidents: 0,
    owners: 1,
    registration: "California, USA",
    tags: "Compact",
  },
  {
    id: 18,
    make: "Honda",
    model: "Civic",
    year: 2015,
    contact: "Noah Wilson",
    price: 75000,
    mileage: 50,
    power: 158,
    speed: 125,
    images: [
      "https://cdn.carbuzz.com/gallery-images/1600/478000/800/478807.jpg",
    ],
    title: "Honda Civic LX Sedan",
    description: "Reliable and fuel-efficient sedan with moderate mileage",
    driven: 12000,
    damages: 1,
    originalColor: "Blue",
    accidents: 1,
    owners: 2,
    registration: "New York, USA",
    tags: "Economical",
  },
  {
    id: 19,
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2022,
    contact: "Ava Johnson",
    price: 350000,
    mileage: 5,
    power: 362,
    speed: 155,
    images: [
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mercedes-Benz/E-Class/8407/1677305821069/front-left-side-47.jpg",
    ],
    title: "2022 Mercedes-Benz E-Class",
    description: "Luxurious sedan with cutting-edge features and low mileage",
    driven: 200,
    damages: 0,
    originalColor: "Silver",
    accidents: 0,
    owners: 1,
    registration: "Paris, France",
    tags: "High-End",
  },
  {
    id: 20,
    make: "Volkswagen",
    model: "Tiguan",
    year: 2018,
    contact: "Harper Martinez",
    price: 110000,
    mileage: 30,
    power: 184,
    speed: 130,
    images: [
      "https://cdntdreditorials2.azureedge.net/cache/e/d/a/4/d/9/eda4d9a9e6f37863b14b9e62827a9ca8cfbe6149.jpg",
    ],
    title: "2018 Volkswagen Tiguan",
    description: "Comfortable and versatile SUV with moderate mileage",
    driven: 10000,
    damages: 0,
    originalColor: "Red",
    accidents: 0,
    owners: 2,
    registration: "Berlin, Germany",
    tags: "Practical",
  },
];
